import Head from "next/head";
import Link from "next/link";
import React from 'react';
import type { GetStaticProps} from "next";

import axios from 'axios';
import Layout from "../../../components/Layout";
import cogoToast from "cogo-toast";

const AddVariant  = ({BACKEND_URL}:any)  => {

  const handleContactInfoSubmit = async(event:any)=>{
    const form = event.currentTarget;
    event.preventDefault();
    if (form.checkValidity() === false) {
      event.stopPropagation();
    }

    if (form.checkValidity() === true) {
      const data = new FormData(event.target);

      await axios.post(BACKEND_URL+"/admin/product-create?type=variant", data).then((res) => {
        cogoToast.success("Data Successfully Saved!");
      }).catch( error => {
        cogoToast.error("Failed!"); 
      });
    }

  }

  return (
    <div className="admin">
      <Head>
        <title>LA SHOOPA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href="/admin/variant" >
        <button>Variant</button>
      </Link>

      <div className="add-product">
        <form onSubmit={handleContactInfoSubmit} >
          <label >Item</label>
          <input type="text"  name="name" placeholder="Enter Variant" required />
        
          <input type="submit" value="Submit" />
        </form>
      </div>
      
    </div>
  );
};

AddVariant.getLayout = function getLayout(page: typeof AddVariant) {
  return <Layout>{page}</Layout>;
};


export const getStaticProps: GetStaticProps = async (context) => {
  return {
    props: {
      BACKEND_URL:  process.env.BACKEND_URL,
    },
  };
};


export default AddVariant;
