import type { GetStaticProps} from "next";
import Head from "next/head";
import Link from "next/link";
import axios from 'axios';
import React, { useEffect } from 'react';
import Layout from "../../components/Layout";


const Order  = (props:(any)  ) => {

  const changeStatus = async(e: any)=>{

    let x = e.target.parentElement.children
    let post = {
        val : "",
        order_id : ""
    }

    for (let index = 0; index < x.length; index++) {
        const element = x[index];
        if(element.tagName === 'SELECT'){
            post.val = element.value
        }

        if(element.tagName === 'UL'){
            if (x[index].children.length) {
                post.order_id = x[index].children[0].value
            }
        }
    }


    await axios.post(props.BACKEND_URL+"/admin/change-ordersss", post).then((res) => {
        alert("Changed Complete")
      }).catch( error => {

      });

    console.log(post)
  }


  return (
    <div className="">
      <Head>
        <title>LA SHOOPA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h3>Order List</h3>
        
      <div className="latest-product product section">
          <div className="main">
            {(() => {
                if (props.data.length) {
                    return (
                      <div className="row">
                      
                      {
                                props.data.map((collection:any,key:any)=>
                                
                                <div key={key} className="column">
                                  {key+1}.

                                    {
                                      collection.map((info:any,key_:any)=>
                                      <ul key={key_}>
                                      {(() => {

                                        if (info) {
                                          return(
                                            <>
                                            <input type="hidden" value={info?.order?.order_id} />
                                            <li>
                                             {info?.order?.status}
                                            </li>

                                            <li>
                                               {info?.under_order?.item}
                                            </li>

                                            <li>
                                               {info?.under_order?.description}
                                            </li>

                                            <li>
                                               {info?.under_order?.price} BDT
                                            </li>

                                            <li>
                                               {info?.under_order?.variant}
                                            </li>

                                            </>
                                          )
                                        }
                                      })()}

                                      </ul>
                                      )
                                    }


                                    <select defaultValue="1">
                                        <option>Processing</option>
                                        <option>Shipped</option>
                                        <option>Delivered</option>
                                    </select>

                                    <button onClick={(e)=>changeStatus(e)}>Submit</button>

                                  </div>
                                
                                )
                              }
                      
                      
                      </div>  
                    )
                } 
            })()}
          </div>
        </div>
    </div>
  );
};

Order.getLayout = function getLayout(page: typeof Order) {
  return <Layout>{page}</Layout>;
};

export const getStaticProps: GetStaticProps = async (context) => {
  const results  = await axios.get(process.env.BACKEND_URL + '/admin/user-order');
  const totalPaginateButton =  Math.trunc( parseInt(results.data.length) /10) + 1

  return {
    props: {
      data:  results.data,
      BACKEND_URL: process.env.BACKEND_URL,
      totalPaginateButton
    },
  };
};

export default Order;
